docker:
  as_root: true
  image: "coala/rultor-python"

merge:
  fast-forward: only
  script:
    - DATE=`date --utc +%Y%m%d%H%M%S`
    - python3 .ci/adjust_version_number.py bears/VERSION -b "$DATE"
    - bash .ci/check_maintainership.sh
    - bash .ci/deploy.pypi.sh

release:
  script: bash .ci/release.sh

decrypt:
  rultor_secrets.sh: "repo/.ci/rultor_secrets.sh.asc"
